In [32]:
import pandas as pd

In [11]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import os

password = os.environ["DB_PASSWORD"]

In [15]:
from sqlalchemy import create_engine

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/foodhub"
)

print("Connection successful!")

Connection successful!

In [16]:
query = "SHOW TABLES"
pd.read_sql(query, engine)

  Tables_in_foodhub
0    product_events

#### 1. Total Records

In [19]:
query = """select count(*) as total_records
            from product_events"""
pd.read_sql(query, engine)

   total_records
0           1898

#### 2. Number of Customers

In [20]:
query = """select count(distinct customer_id) as total_customers
           from product_events"""
pd.read_sql(query, engine)

   total_customers
0             1200

#### 3. Number of Restaurants

In [21]:
query = """select count(distinct restaurant_name) as total_restaurants
           from product_events"""
pd.read_sql(query, engine)

   total_restaurants
0                178

#### 4. Number of Cuisine Types

In [22]:
query = """select count(distinct cuisine_type) as total_cuisines
           from product_events"""
pd.read_sql(query, engine)

   total_cuisines
0              14

#### 5. Date Range

In [23]:
query = """select
                min(session_date) as first_session,
                max(session_date) as last_session
           from product_events"""
pd.read_sql(query, engine)

         first_session         last_session
0  2024-01-01 00:02:06  2024-01-30 23:54:21

#### 6. Cities Covered

In [25]:
query = """select distinct city
           from product_events"""
pd.read_sql(query, engine)

        city
0  Hyderabad
1  Bangalore
2    Chennai
3     Mumbai
4      Delhi
5       Pune

#### 7. Device Types

In [26]:
query = """select
                device_type,
                count(*) as users
           from product_events
           group by device_type"""
pd.read_sql(query, engine)

  device_type  users
0     Android   1403
1         iOS    495

#### 8. Acquisition Channels

In [27]:
query = """select
                acquisition_channel,
                count(*) users
           from product_events
           group by acquisition_channel
           order by users desc"""
pd.read_sql(query, engine)

  acquisition_channel  users
0             Organic    883
1          Google Ads    314
2            Referral    266
3           Instagram    265
4            Facebook    170

Organic acquisition channel brings the most customers

#### 9. Control vs Variant

In [28]:
query = """select
                experiment_group,
                count(*) users
           from product_events
           group by experiment_group"""
pd.read_sql(query, engine)

  experiment_group  users
0          Variant    951
1          Control    947

This checks if the A/B test groups are balanced.

#### 10. Missing Values Check

In [30]:
query = """select
                sum(customer_id is null) customer_null,
                sum(city is null) city_null,
                sum(rating is null) rating_null,
                sum(delivery_time is null) delivery_null
           from product_events"""
pd.read_sql(query, engine)

   customer_null  city_null  rating_null  delivery_null
0            0.0        0.0          0.0            0.0