In [1]:
import pandas as pd

In [2]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import os

password = os.environ["DB_PASSWORD"]

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
                        f"mysql+pymysql://root:{password}@localhost:3306/foodhub"
                        )

print("Connection successful!")

Connection successful!

### SECTION 1: Revenue Analysis

#### 1. Total Revenue

In [6]:
query = """select
                round(sum(cost_of_the_order),2) as total_revenue
           from product_events"""
pd.read_sql(query, engine)

   total_revenue
0       31314.82

#### 2. Average Order Value (AOV)

In [7]:
query = """select
                round(avg(cost_of_the_order),2) as average_order_value
           from product_events;"""
pd.read_sql(query, engine)

   average_order_value
0                 16.5

#### 3. Maximum & Minimum Order Value

In [8]:
query = """select
                max(cost_of_the_order) as highest_order,
                min(cost_of_the_order) as lowest_order
           from product_events"""
pd.read_sql(query, engine)

   highest_order  lowest_order
0          35.41          4.47

### SECTION 2: City Performance

#### 4. Revenue by City

In [9]:
query = """select
                city,
                round(sum(cost_of_the_order),2) as revenue
           from product_events
           group by city
           order by revenue desc"""
pd.read_sql(query, engine)

        city  revenue
0  Bangalore  9182.75
1  Hyderabad  6126.00
2     Mumbai  6092.04
3      Delhi  4553.58
4    Chennai  2976.38
5       Pune  2384.07

#### 5. Average Rating by City

In [10]:
query = """select
                city,
                round(avg(rating),2) as avg_rating
           from product_events
           group by city
           order by avg_rating desc"""
pd.read_sql(query, engine)

        city  avg_rating
0       Pune        2.74
1  Hyderabad        2.66
2  Bangalore        2.66
3    Chennai        2.66
4      Delhi        2.65
5     Mumbai        2.64

#### 6. Average Delivery Time by City

In [11]:
query = """select
                city,
                round(avg(delivery_time),2) as avg_delivery_time
           from product_events
           group by city
           order by avg_delivery_time"""
pd.read_sql(query, engine)

        city  avg_delivery_time
0     Mumbai              23.83
1       Pune              23.85
2  Hyderabad              24.06
3  Bangalore              24.14
4    Chennai              24.45
5      Delhi              24.74

### SECTION 3: Restaurant Performance

#### 16. Customers by Acquisition Channel

In [12]:
query = """select
                acquisition_channel,
                count(distinct customer_id) as customers
           from product_events
           group by acquisition_channel
           order by customers desc"""
pd.read_sql(query, engine)

  acquisition_channel  customers
0             Organic        556
1          Google Ads        193
2           Instagram        178
3            Referral        171
4            Facebook        102

#### 18. Average Order Value by Acquisition Channel

In [13]:
query = """select
                acquisition_channel,
                round(avg(cost_of_the_order),2) as avg_order_value
           from product_events
           group by acquisition_channel
           order by avg_order_value desc;"""
pd.read_sql(query, engine)

  acquisition_channel  avg_order_value
0            Referral            16.86
1            Facebook            16.60
2             Organic            16.46
3          Google Ads            16.44
4           Instagram            16.25

#### Revenue Contribution %

In [15]:
query = """ select
                city,
                round(sum(cost_of_the_order),2) as revenue,
                round(
                    sum(cost_of_the_order) * 100 /
                    (select sum(cost_of_the_order) from product_events),
                     2
                     ) AS revenue_percentage
           from product_events
           group by city
           order by revenue desc"""
pd.read_sql(query, engine)

        city  revenue  revenue_percentage
0  Bangalore  9182.75               29.32
1  Hyderabad  6126.00               19.56
2     Mumbai  6092.04               19.45
3      Delhi  4553.58               14.54
4    Chennai  2976.38                9.50
5       Pune  2384.07                7.61