In [1]:
import pandas as pd

In [2]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import os

password = os.environ["DB_PASSWORD"]

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
                        f"mysql+pymysql://root:{password}@localhost:3306/foodhub"
                        )

print("Connection successful!")

Connection successful!

#### 1. Users in Each Experiment Group

In [5]:
query = """select
                experiment_group,
                count(*) as total_users
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  total_users
0          Variant          951
1          Control          947

#### 2. Recommendation Click-Through Rate (CTR)

In [20]:
query = """select
                experiment_group,
                round(avg(recommendation_clicked) * 100, 2) as ctr
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group    ctr
0          Variant  30.18
1          Control  19.32

#### 3. Cart Creation Rate

In [21]:
query = """select
                experiment_group,
                round(avg(cart_created) * 100, 2) as cart_creation_rate
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  cart_creation_rate
0          Variant               64.04
1          Control               60.82

#### 4. Average Order Value (AOV)

In [22]:
query = """select
                experiment_group,
                round(avg(cost_of_the_order), 2) as average_order_value
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  average_order_value
0          Variant                16.67
1          Control                16.32

#### 5. Total Revenue by Experiment Group

In [23]:
query = """select
                experiment_group,
                round(sum(cost_of_the_order), 2) as total_revenue
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  total_revenue
0          Variant       15857.88
1          Control       15456.94

#### 6. Average Rating

In [24]:
query = """select
                experiment_group,
                round(avg(rating), 2) as average_rating
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  average_rating
0          Variant            2.68
1          Control            2.64

#### 7. Average Delivery Time

In [25]:
query = """select
                experiment_group,
                round(avg(delivery_time), 2) as average_delivery_time
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  average_delivery_time
0          Variant                  23.99
1          Control                  24.33

#### 8. Average Food Preparation Time

In [26]:
query = """select
                experiment_group,
                round(avg(food_preparation_time), 2) as average_preparation_time
           from product_events
           group by experiment_group
"""

pd.read_sql(query, engine)

  experiment_group  average_preparation_time
0          Variant                     27.35
1          Control                     27.39

#### 9. Recommendation Seen %

In [13]:
query = """select
                experiment_group,
                round(avg(recommendation_seen) * 100, 2) as recommendation_seen_rate
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  recommendation_seen_rate
0          Variant                     95.90
1          Control                     94.93

#### 10. Coupon Usage %

In [14]:
query = """select
                experiment_group,
                round(avg(coupon_used) * 100, 2) as coupon_usage_rate
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

  experiment_group  coupon_usage_rate
0          Variant              32.18
1          Control              35.90

#### 11. Revenue by City and Experiment Group

In [15]:
query = """select
                city,
                experiment_group,
                round(sum(cost_of_the_order),2) as revenue
           from product_events
           group by city, experiment_group
           order by city, revenue desc"""

pd.read_sql(query, engine)

         city experiment_group  revenue
0   Bangalore          Variant  4668.66
1   Bangalore          Control  4514.09
2     Chennai          Control  1583.04
3     Chennai          Variant  1393.34
4       Delhi          Control  2384.88
5       Delhi          Variant  2168.70
6   Hyderabad          Control  3180.93
7   Hyderabad          Variant  2945.07
8      Mumbai          Variant  3398.49
9      Mumbai          Control  2693.55
10       Pune          Variant  1283.62
11       Pune          Control  1100.45

#### 12. Cart Creation Rate by Device

In [16]:
query = """select
                device_type,
                experiment_group,
                round(avg(cart_created) * 100,2) as cart_rate
           from product_events
           group by device_type, experiment_group"""

pd.read_sql(query, engine)

  device_type experiment_group  cart_rate
0     Android          Variant      65.04
1     Android          Control      61.56
2         iOS          Control      58.68
3         iOS          Variant      61.26

#### 13. CTR by Acquisition Channel

In [17]:
query = """select
                acquisition_channel,
                experiment_group,
                round(avg(recommendation_clicked) * 100,2) as ctr
           from product_events
           group by acquisition_channel, experiment_group
           order by acquisition_channel"""

pd.read_sql(query, engine)

  acquisition_channel experiment_group    ctr
0            Facebook          Control  17.07
1            Facebook          Variant  34.09
2          Google Ads          Control  24.83
3          Google Ads          Variant  27.27
4           Instagram          Control  19.42
5           Instagram          Variant  25.40
6             Organic          Control  18.68
7             Organic          Variant  32.83
8            Referral          Control  16.88
9            Referral          Variant  25.89

#### 14. Average Order Value by Device

In [18]:
query = """select
                device_type,
                experiment_group,
                round(avg(cost_of_the_order),2) as average_order_value
           from product_events
           group by device_type, experiment_group"""

pd.read_sql(query, engine)

  device_type experiment_group  average_order_value
0     Android          Variant                16.92
1     Android          Control                16.43
2         iOS          Control                16.01
3         iOS          Variant                16.01

#### 15. Complete A/B Test KPI Dashboard Query

In [27]:
query = """select
                experiment_group,
                
                count(*) as total_users,
                round(avg(recommendation_clicked) * 100,2) as ctr,
                round(avg(cart_created) * 100,2) as cart_creation_rate,

                round(avg(cost_of_the_order),2) as average_order_value,
                round(avg(delivery_time),2) as average_delivery_time,
                round(avg(rating),2) as average_rating,

                round(avg(coupon_used) * 100,2) as coupon_usage_rate

           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

,experiment_group,total_users,ctr,cart_creation_rate,average_order_value,average_delivery_time,average_rating,coupon_usage_rate
0,Variant,951,30.18,64.04,16.67,23.99,2.68,32.18
1,Control,947,19.32,60.82,16.32,24.33,2.64,35.90