In [1]:
import pandas as pd

In [2]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import os

password= os.environ["DB_PASSWORD"]

In [7]:
from sqlalchemy import create_engine

engine = create_engine(
                        f"mysql+pymysql://root:{password}@localhost:3306/foodhub"
                        )

print("Connection successful!")

Connection successful!

#### 1. Top Restaurant Within Each City

In [12]:
query = """
select *
from (
    select
        city,
        restaurant_name,
        round(sum(cost_of_the_order),2) as revenue,
        rank() over(
            partition by city
            order by sum(cost_of_the_order) desc
        ) as city_rank
    from product_events
    group by city, restaurant_name
) t
where city_rank = 1
"""

pd.read_sql(query, engine)

        city    restaurant_name  revenue  city_rank
0  Bangalore        Shake Shack  1083.94          1
1    Chennai  The Meatball Shop   445.96          1
2      Delhi        Shake Shack   518.55          1
3  Hyderabad        Shake Shack   878.32          1
4     Mumbai        Shake Shack   511.78          1
5       Pune        Shake Shack   290.51          1

#### 2. Moving Average (3 Orders)

In [16]:
query = """
select
    session_date,
    cost_of_the_order,
    round(
        avg(cost_of_the_order) over(
            order by session_date
            rows between 2 preceding and current row
        ),
    2) as moving_average
from product_events
"""

pd.read_sql(query, engine)

             session_date  cost_of_the_order  moving_average
0     2024-01-01 00:02:06              25.17           25.17
1     2024-01-01 00:06:44              19.45           22.31
2     2024-01-01 00:50:51              21.83           22.15
3     2024-01-01 00:54:27              29.34           23.54
4     2024-01-01 01:28:07              13.00           21.39
...                   ...                ...             ...
1893  2024-01-30 21:36:24               9.17           17.90
1894  2024-01-30 22:03:51              29.05           17.82
1895  2024-01-30 22:30:44               6.74           14.99
1896  2024-01-30 22:46:49              14.07           16.62
1897  2024-01-30 23:54:21              16.30           12.37

[1898 rows x 3 columns]

#### 3. Revenue Contribution %

In [18]:
query = """
select
    city,
    round(sum(cost_of_the_order),2) as revenue,
    round(
        sum(cost_of_the_order)*100/
        sum(sum(cost_of_the_order)) over(),
    2) as revenue_percentage
from product_events
group by city
"""

pd.read_sql(query, engine)

        city  revenue  revenue_percentage
0  Hyderabad  6126.00               19.56
1  Bangalore  9182.75               29.32
2    Chennai  2976.38                9.50
3     Mumbai  6092.04               19.45
4      Delhi  4553.58               14.54
5       Pune  2384.07                7.61

#### 4. Highest Revenue Restaurant by Cuisine

In [21]:
query = """
select *
from (
    select
        cuisine_type,
        restaurant_name,
        round(sum(cost_of_the_order),2) as revenue,
        row_number() over(
            partition by cuisine_type
            order by sum(cost_of_the_order) desc
        ) as rn
    from product_events
    group by cuisine_type, restaurant_name
) t
where rn = 1
"""

pd.read_sql(query, engine)

      cuisine_type                      restaurant_name  revenue  rn
0         American                          Shake Shack  3579.53   1
1          Chinese                     RedFarm Broadway   965.13   1
2           French                Balthazar Boulangerie   187.01   1
3           Indian                     Tamarind TriBeCa   426.71   1
4          Italian                    The Meatball Shop  1821.01   1
5         Japanese                    Blue Ribbon Sushi  1903.95   1
6           Korean                         Cho Dang Gol    85.19   1
7    Mediterranean                    Jack's Wife Freda   416.75   1
8          Mexican  Chipotle Mexican Grill 199 Delivery   491.69   1
9   Middle Eastern                     ilili Restaurant   343.22   1
10        Southern           Hill Country Fried Chicken   292.39   1
11         Spanish                             Boqueria   169.67   1
12            Thai                 Lantern Thai Kitchen    78.29   1
13      Vietnamese                           V-Nam Cafe    52.48   1