In [1]:
import pandas as pd

In [2]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import os

password= os.environ["DB_PASSWORD"]

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
                        f"mysql+pymysql://root:{password}@localhost:3306/foodhub"
                        )

print("Connection successful!")

Connection successful!

#### 1. Which city generated the highest revenue?

In [31]:
query = """select
                city,
                round(sum(cost_of_the_order),2) as total_revenue
           from product_events
           group by city
           order by total_revenue desc"""

pd.read_sql(query, engine)

        city  total_revenue
0  Bangalore        9182.75
1  Hyderabad        6126.00
2     Mumbai        6092.04
3      Delhi        4553.58
4    Chennai        2976.38
5       Pune        2384.07

#### 2. Which acquisition channel brings the highest-value customers?

In [32]:
query = """select
                acquisition_channel,
                count(distinct customer_id) as customers,
                round(avg(cost_of_the_order),2) as average_order_value,
                round(sum(cost_of_the_order),2) as total_revenue
           from product_events
           group by acquisition_channel
           order by total_revenue desc"""

pd.read_sql(query, engine)

  acquisition_channel  customers  average_order_value  total_revenue
0             Organic        556                16.46       14537.92
1          Google Ads        193                16.44        5162.88
2            Referral        171                16.86        4483.98
3           Instagram        178                16.25        4307.53
4            Facebook        102                16.60        2822.51

#### 3. Which cuisine has the highest customer satisfaction?

In [33]:
query = """select
                cuisine_type,
                round(avg(rating),2) as average_rating,
                count(*) as total_orders
           from product_events
           group by cuisine_type
           having count(*) >= 10
           order by average_rating desc"""

pd.read_sql(query, engine)

      cuisine_type  average_rating  total_orders
0         Southern            3.29            17
1           Indian            3.11            73
2   Middle Eastern            2.94            49
3    Mediterranean            2.93            46
4           Korean            2.85            13
5          Mexican            2.75            77
6         American            2.71           584
7          Chinese            2.68           215
8         Japanese            2.54           470
9          Italian            2.52           298
10         Spanish            2.42            12
11          French            2.39            18
12            Thai            2.21            19

#### 4. Which restaurants should be promoted?

In [34]:
query = """select
                restaurant_name,
                round(avg(rating),2) as average_rating,
                round(avg(delivery_time),2) as average_delivery_time,
                round(sum(cost_of_the_order),2) as revenue
           from product_events
           group by restaurant_name
           having average_rating >= 4.5
           order by revenue desc"""

pd.read_sql(query, engine)

,restaurant_name,average_rating,average_delivery_time,revenue
0,Dickson's Farmstand Meats,4.67,22.67,60.93
1,Hummus Place,4.67,24.33,54.95
2,Song Thai Restaurant & Bar,5.00,27.00,53.40
3,Le Grainne Cafe,4.50,23.00,45.21
4,Hot Kitchen,5.00,26.50,42.54
5,Kambi Ramen House,5.00,19.00,32.93
6,Haru Gramercy Park,5.00,32.00,29.83
7,Klong,5.00,24.00,29.05
8,67 Burger,5.00,28.00,29.05
9,Big Daddy's,5.00,19.00,26.92
10,Socarrat Paella Bar,5.00,20.00,25.22
11,Philippe Chow,5.00,30.00,24.20
12,Bukhara Grill,5.00,21.50,23.72
13,Anjappar Chettinad,5.00,26.00,16.44
14,Chote Nawab,5.00,30.00,16.15
15,Cafe de La Esquina,5.00,21.00,16.06
16,Galli Restaurant,5.00,16.00,16.06
17,Taro Sushi,5.00,32.00,16.05
18,Dig Inn Seasonal Market,5.00,26.00,15.71
19,Moonstruck on Second,5.00,20.00,14.94
20,Dos Caminos Soho,5.00,30.00,12.66
21,Samurai Mama,5.00,18.00,11.64
22,Balade,5.00,24.00,9.22
23,Chola Eclectic Indian Cuisine,5.00,28.00,8.73
24,wichcraft,5.00,28.00,8.10
25,Cipriani Le Specialita,5.00,30.00,5.92
26,Hunan Manor,5.00,26.00,5.72

#### 5. Which customers should receive loyalty rewards?

In [35]:
query = """select
                customer_id,
                count(*) as total_orders,
                round(sum(cost_of_the_order),2) as total_spend
           from product_events
           group by customer_id
           having total_orders >= 3
           order by total_spend desc"""

pd.read_sql(query, engine)

     customer_id  total_orders  total_spend
0          52832            13       225.80
1         250494             8       183.83
2          47440            10       158.18
3         276192             7       146.46
4          83287             9       139.31
..           ...           ...          ...
144        14869             3        30.27
145       105837             3        29.06
146       325285             3        25.23
147       237616             3        23.63
148       103852             3        22.31

[149 rows x 3 columns]

#### 6. Which customers should receive discount coupons?

In [36]:
query = """select
                customer_id,
                round(avg(cost_of_the_order),2) as average_order_value,
                sum(cart_created) as carts_created,
                sum(coupon_used) as coupons_used
           from product_events
           group by customer_id
           having average_order_value < 15
           order by average_order_value"""

pd.read_sql(query, engine)

     customer_id  average_order_value  carts_created  coupons_used
0         133617                 4.75            0.0           0.0
1          50123                 4.85            1.0           0.0
2         318665                 4.90            1.0           1.0
3         339144                 5.05            1.0           0.0
4          64754                 5.34            0.0           0.0
..           ...                  ...            ...           ...
591       115519                14.90            1.0           1.0
592       128353                14.94            1.0           0.0
593        94115                14.94            1.0           1.0
594       310051                14.99            1.0           1.0
595       105068                14.99            0.0           0.0

[596 rows x 4 columns]

#### 7. Does faster delivery improve ratings?

In [37]:
query = """select
                case
                    when delivery_time <= 20 then 'Fast'
                    when delivery_time <= 30 then 'Medium'
                    else 'Slow'
                end as delivery_speed,
                round(avg(rating),2) as average_rating,
                count(*) as total_orders
           from product_events
           group by delivery_speed"""

pd.read_sql(query, engine)

  delivery_speed  average_rating  total_orders
0           Fast            2.67           516
1         Medium            2.65          1233
2           Slow            2.70           149

#### 8. Which device generates more revenue?

In [38]:
query = """select
                device_type,
                round(sum(cost_of_the_order),2) as total_revenue,
                round(avg(cost_of_the_order),2) as average_order_value
           from product_events
           group by device_type
           order by total_revenue desc"""

pd.read_sql(query, engine)

  device_type  total_revenue  average_order_value
0     Android       23388.99                16.67
1         iOS        7925.83                16.01

#### 9. Compare Control vs Variant performance

In [39]:
query = """select
                experiment_group,
                count(*) as users,
                round(avg(recommendation_clicked)*100,2) as ctr,
                round(avg(cart_created)*100,2) as cart_rate,
                round(avg(cost_of_the_order),2) as average_order_value,
                round(avg(rating),2) as average_rating
           from product_events
           group by experiment_group"""

pd.read_sql(query, engine)

,experiment_group,users,ctr,cart_rate,average_order_value,average_rating
0,Variant,951,30.18,64.04,16.67,2.68
1,Control,947,19.32,60.82,16.32,2.64

#### 10. Which city has the best delivery efficiency?

In [40]:
query = """select
                city,
                round(avg(food_preparation_time),2) as prep_time,
                round(avg(delivery_time),2) as delivery_time,
                round(avg(rating),2) as average_rating
           from product_events
           group by city
           order by delivery_time desc"""

pd.read_sql(query, engine)

        city  prep_time  delivery_time  average_rating
0      Delhi      26.76          24.74            2.65
1    Chennai      27.54          24.45            2.66
2  Bangalore      27.39          24.14            2.66
3  Hyderabad      27.28          24.06            2.66
4       Pune      27.92          23.85            2.74
5     Mumbai      27.63          23.83            2.64

#### 11. Top 5 restaurants in each city

In [41]:
query = """select *
           from(
                select
                    city,
                    restaurant_name,
                    round(sum(cost_of_the_order),2) as revenue,
                    row_number() over(
                        partition by city
                        order by sum(cost_of_the_order) desc
                    ) as rn
                from product_events
                group by city, restaurant_name
                )t
           where rn <= 5"""

pd.read_sql(query, engine)

         city            restaurant_name  revenue  rn
0   Bangalore                Shake Shack  1083.94   1
1   Bangalore          The Meatball Shop   710.40   2
2   Bangalore          Blue Ribbon Sushi   660.89   3
3   Bangalore  Blue Ribbon Fried Chicken   515.14   4
4   Bangalore                        TAO   322.83   5
5     Chennai          The Meatball Shop   445.96   1
6     Chennai                Shake Shack   296.43   2
7     Chennai             RedFarm Hudson   218.17   3
8     Chennai          Blue Ribbon Sushi   209.65   4
9     Chennai                       Parm   209.64   5
10      Delhi                Shake Shack   518.55   1
11      Delhi          Blue Ribbon Sushi   284.33   2
12      Delhi  Blue Ribbon Fried Chicken   274.61   3
13      Delhi             RedFarm Hudson   260.63   4
14      Delhi                   Rubirosa   183.69   5
15  Hyderabad                Shake Shack   878.32   1
16  Hyderabad          Blue Ribbon Sushi   339.98   2
17  Hyderabad          The Meatball Shop   339.93   3
18  Hyderabad  Blue Ribbon Fried Chicken   275.05   4
19  Hyderabad           RedFarm Broadway   244.76   5
20     Mumbai                Shake Shack   511.78   1
21     Mumbai  Blue Ribbon Fried Chicken   408.56   2
22     Mumbai          The Meatball Shop   363.14   3
23     Mumbai                       Parm   264.00   4
24     Mumbai           RedFarm Broadway   238.14   5
25       Pune                Shake Shack   290.51   1
26       Pune                Han Dynasty   211.10   2
27       Pune          Blue Ribbon Sushi   175.60   3
28       Pune  Blue Ribbon Fried Chicken   151.67   4
29       Pune             Nobu Next Door   140.85   5

#### 12. Monthly revenue trend

In [43]:
query = """select
                date_format(session_date,'%%y-%%m') as month,
                round(sum(cost_of_the_order),2) as revenue
           from product_events
           group by month
           order by month"""

pd.read_sql(query, engine)

   month   revenue
0  24-01  31314.82

#### 13. Which acquisition channel has the highest CTR?

In [28]:
query = """select
                acquisition_channel,
                round(avg(recommendation_clicked)*100,2) as ctr
           from product_events
           group by acquisition_channel
           order by ctr desc"""

pd.read_sql(query, engine)

  acquisition_channel    ctr
0          Google Ads  26.11
1             Organic  26.05
2            Facebook  25.88
3           Instagram  22.26
4            Referral  20.68

#### 14. Which customer segment contributes the most revenue?

In [29]:
query = """with customer_summary as(select
                                        customer_id,
                                        sum(cost_of_the_order) as total_spend
                                    from product_events
                                    group by customer_id
                                    )

           select
               case
                   when total_spend >= 100 then 'High Value'
                   when total_spend >= 50 then 'Medium Value'
                   else 'Low Value'
               end as customer_segment,
               count(*) as customers,
               round(sum(total_spend),2) as revenue
           from customer_summary
           group by customer_segment
           order by revenue desc"""

pd.read_sql(query, engine)

  customer_segment  customers   revenue
0        Low Value       1083  22623.01
1     Medium Value        103   6823.46
2       High Value         14   1868.35

#### 15. Executive KPI Dashboard Query

In [42]:
query = """select
                count(*) as total_orders,
                count(distinct customer_id) as total_customers,
                round(sum(cost_of_the_order),2) as total_revenue,
                round(avg(cost_of_the_order),2) as average_order_value,

                round(avg(delivery_time),2) as average_delivery_time,
                round(avg(food_preparation_time),2) as average_preparation_time,

                round(avg(rating),2) as average_rating,

                round(avg(recommendation_clicked)*100,2) as recommendation_ctr,
                round(avg(cart_created)*100,2) as cart_creation_rate,
                round(avg(coupon_used)*100,2) as coupon_usage_rate

           from product_events"""

pd.read_sql(query, engine)

,total_orders,total_customers,total_revenue,average_order_value,average_delivery_time,average_preparation_time,average_rating,recommendation_ctr,cart_creation_rate,coupon_usage_rate
0,1898,1200,31314.82,16.5,24.16,27.37,2.66,24.76,62.43,34.04